from __future__ import annotations

from pathlib import Path
import argparse
import json

import pandas as pd
import rasterio


HEADER = r"""// Generated by scripts/generate_gee_exports.py
// Paste into https://code.earthengine.google.com and run the Export tasks.

var pairs = __PAIR_SPECS__;
var exportFolder = '__EXPORT_FOLDER__';

function nextDay(dateText) {
  return ee.Date(dateText).advance(1, 'day');
}

function exportS1(pair, windowName, dateText) {
  var region = ee.Geometry.Rectangle(pair.bounds, pair.crs, false);
  var collection = ee.ImageCollection('COPERNICUS/S1_GRD')
    .filterBounds(region)
    .filterDate(ee.Date(dateText), nextDay(dateText))
    .filter(ee.Filter.eq('instrumentMode', 'IW'))
    .filter(ee.Filter.eq('orbitProperties_pass', pair.orbitPass))
    .filter(ee.Filter.eq('relativeOrbitNumber_start', pair.relativeOrbit))
    .filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VV'))
    .filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VH'))
    .select(['VV', 'VH']);
  print(pair.pairId + ' S1 ' + windowName + ' scenes', collection.size());
  var sar = collection.mosaic().clip(region);
  var ratio = sar.select('VV').subtract(sar.select('VH')).rename('VV_VH_ratio');
  var output = sar.addBands(ratio).toFloat().unmask(-9999);
  Export.image.toDrive({
    image: output,
    description: pair.pairId + '_S1_' + windowName,
    folder: exportFolder,
    fileNamePrefix: pair.pairId + '__S1_' + windowName + '_' + dateText,
    region: region,
    crs: pair.crs,
    crsTransform: pair.transform,
    maxPixels: 1e10,
    fileFormat: 'GeoTIFF',
    formatOptions: {cloudOptimized: true, noData: -9999}
  });
}

function maskS2(image) {
  var scl = image.select('SCL');
  var valid = scl.neq(1).and(scl.neq(3)).and(scl.neq(8))
    .and(scl.neq(9)).and(scl.neq(10)).and(scl.neq(11));
  return image.updateMask(valid);
}

function exportS2(pair, windowName, dateText) {
  if (!dateText) return;
  var region = ee.Geometry.Rectangle(pair.bounds, pair.crs, false);
  var collection = ee.ImageCollection('COPERNICUS/S2_SR_HARMONIZED')
    .filterBounds(region)
    .filterDate(ee.Date(dateText), nextDay(dateText))
    .map(maskS2);
  print(pair.pairId + ' S2 ' + windowName + ' scenes', collection.size());
  var source = collection.median().clip(region);
  var reflectance = source.select(['B2', 'B3', 'B4', 'B8', 'B11', 'B12']).multiply(0.0001);
  var b2 = reflectance.select('B2');
  var b3 = reflectance.select('B3');
  var b4 = reflectance.select('B4');
  var b8 = reflectance.select('B8');
  var b11 = reflectance.select('B11');
  var b12 = reflectance.select('B12');
  var ndwi = b3.subtract(b8).divide(b3.add(b8)).rename('NDWI');
  var mndwi = b3.subtract(b11).divide(b3.add(b11)).rename('MNDWI');
  var ndvi = b8.subtract(b4).divide(b8.add(b4)).rename('NDVI');
  var aweish = b2.add(b3.multiply(2.5))
    .subtract(b8.add(b11).multiply(1.5))
    .subtract(b12.multiply(0.25)).rename('AWEISH');
  var output = reflectance.select(['B3', 'B4', 'B8', 'B11'])
    .addBands([ndwi, mndwi, ndvi, aweish]).toFloat().unmask(-9999);
  Export.image.toDrive({
    image: output,
    description: pair.pairId + '_S2_' + windowName,
    folder: exportFolder,
    fileNamePrefix: pair.pairId + '__SENTINEL2_' + windowName + '_' + dateText,
    region: region,
    crs: pair.crs,
    crsTransform: pair.transform,
    maxPixels: 1e10,
    fileFormat: 'GeoTIFF',
    formatOptions: {cloudOptimized: true, noData: -9999}
  });
}

pairs.forEach(function(pair) {
  exportS1(pair, 'pre', pair.datePreSar);
  exportS1(pair, 'peak', pair.datePeakSar);
  exportS2(pair, 'pre', pair.datePreOpt);
  exportS2(pair, 'peak', pair.datePeakOpt);
});
"""


def build_specs(data_root: Path) -> list[dict]:
    pairs = pd.read_csv(data_root / "pairs.csv")
    specs: list[dict] = []
    for pair in pairs.itertuples(index=False):
        reference = data_root / pair.reference_mask
        with rasterio.open(reference) as source:
            transform = source.transform
            bounds = source.bounds
            specs.append({
                "pairId": pair.pair_id,
                "aoiId": pair.aoi_id,
                "eventId": pair.event_id,
                "crs": str(source.crs),
                "bounds": [bounds.left, bounds.bottom, bounds.right, bounds.top],
                "transform": [transform.a, transform.b, transform.c, transform.d, transform.e, transform.f],
                "width": source.width,
                "height": source.height,
                "datePreSar": pair.date_pre_sar,
                "datePeakSar": pair.date_peak_sar,
                "datePreOpt": None if pd.isna(pair.date_pre_opt) else pair.date_pre_opt,
                "datePeakOpt": None if pd.isna(pair.date_peak_opt) else pair.date_peak_opt,
                "orbitPass": pair.orbit_pass,
                "relativeOrbit": int(pair.relative_orbit),
            })
    return specs


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate aligned Google Earth Engine export tasks")
    parser.add_argument("--data-root", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=Path("outputs/gee_export.js"))
    parser.add_argument("--drive-folder", default="hydrowatch_amur")
    args = parser.parse_args()
    script = HEADER.replace("__PAIR_SPECS__", json.dumps(build_specs(args.data_root), ensure_ascii=False, indent=2))
    script = script.replace("__EXPORT_FOLDER__", args.drive_folder.replace("'", ""))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(script, encoding="utf-8")
    print(f"Generated {args.output}")


if __name__ == "__main__":
    main()
